你好，我是周爱民，欢迎回到我的专栏。

从之前的课程中，你应该已经对语句执行和函数执行有了基本的了解。事实上，这两种执行其实都是对**顺序**、**分支**与**循环**三种逻辑在语义上的表达。

也就是说，不论一门语言的语法有什么特异之处，它对“执行逻辑”都可以归纳到这三种语义的表达方式上来。这种说法事实上也并不特别严谨，因为这三种基本逻辑还存在进一步抽象的空间（这些也会是我将来会讨论到的内容，今天暂且不论）。

今天这一讲中，主要讨论的是第二种执行的一些细节，也就是对“函数执行”的进一步补充。

在上一讲中，我有意将函数分成三个语义组件来讲述。我相信在绝大多数的情况下，或者在绝大多数的语言教学中，都是不必要这样做的。这三个语义组件分别是指参数、执行体和结果，将它们分开来讨论，最主要的价值就在于：通过改造这三个语义组件的不同部分，我们可以得到不同的“函数式的”执行特征与效果。换而言之，可以通过更显式的、特指的或与应用概念更贴合的语法来表达新的语义。与所谓“特殊可执行结构”一样，这些语义也用于映射某种固定的、确定的逻辑。

语言的设计，本质就是为确定的语义赋以恰当的语法表达。

## 递归与迭代

如果循环是一种确定的语义，那么如何在函数执行中为它设计合适的语法表达呢？
<div><strong>精选留言（11）</strong></div><ul>
<li><img src="https://static001.geekbang.org/account/avatar/00/15/1f/86/3a7eeac4.jpg" width="30px"><span>leslee</span> 👍（4） 💬（1）<div>1. 他可以手动调用..., 在you dont know js 里面说过这个 .throw 可以委托异常.
2. 这是由他的语义决定的, 如果他是一个语句, 那他就不能跟表达式连用, 如果他是一个表达式, 那他的返回值又显得有点多余.
3. 
```js
function foo4(x = 5) {
      return {
        next: () =&gt; {
          return { done: !x, value: x &amp;&amp; x-- };
        },
        &quot;return&quot;: () =&gt; {
          return { done: true, value: &#39;恭喜发财&#39; }
        },
        &quot;throw&quot;: () =&gt; {
          console.log(&quot;THROW!&quot;)
        }
      }
    }


    let x = new Object;
    x[Symbol.iterator] = foo4
aaa: for (let item of x) {
      console.log(item, &#39;w&#39;)
      for (let item of x) {
        console.log(item, &#39;i&#39;)
        continue aaa;
      }
    }
&#47;&#47;  echo &#39;return&#39; x2
&#47;&#47; 当return 函数返回undefined 的时候会报这个错 Iterator result undefined is not an object
```
被我试出来了, 当return函数返回undefined , 且嵌套循环且continue带有外层循环语句的标签的时候, 他会触发两次return, 缺一个条件都不行. 当return函数返回一个正常的迭代器对象`{done:true, value: &#39;xxx&#39;}`, 他会输出5个return, 这个return应该由内层的forof 发出, 因为内层的循环直接被打断了, 继续下去的是外层循环, 单层循环不行是因为 continue 的语义并不是打断&#47;结束, 是这样理解么老师, 这里面还有其他的豆子么,老师.
4. 把x展开, 返回迭代值 , 如果 没有 * 返回的将是迭代器函数, .</div>2019-12-26</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/11/a3/ea/53333dd5.jpg" width="30px"><span>HoSalt</span> 👍（3） 💬（1）<div>老师，为什么fn(...args)怎么变成了一个个的参数，而在{...args}怎么变成了对象属性的一部分，这是谁控制的？</div>2020-05-18</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/0f/78/51/4790e13e.jpg" width="30px"><span>Smallfly</span> 👍（1） 💬（2）<div>
&#47;&#47; 迭代函数
function foo(x = 5) {
  return {
    next: () =&gt; {
      return {done: !x, value: x &amp;&amp; x--};
    }
  }
}

const tor = foo();
const names = Object.getOwnPropertyNames(tor.constructor.prototype);

console.log(names);
&#47;*
  [ &#39;constructor&#39;,
  &#39;__defineGetter__&#39;,
  &#39;__defineSetter__&#39;,
  &#39;hasOwnProperty&#39;,
  &#39;__lookupGetter__&#39;,
  &#39;__lookupSetter__&#39;,
  &#39;isPrototypeOf&#39;,
  &#39;propertyIsEnumerable&#39;,
  &#39;toString&#39;,
  &#39;valueOf&#39;,
  &#39;__proto__&#39;,
  &#39;toLocaleString&#39; ]
*&#47;

请问老师我用 node 执行上面的代码，为什么跟文中的以下输出不一致呢。

&gt; Object.getOwnPropertyNames(tor.constructor.prototype)
[ &#39;constructor&#39;, &#39;next&#39;, &#39;return&#39;, &#39;throw&#39; ]
</div>2020-01-16</li><br/><li><img src="" width="30px"><span>Sam</span> 👍（0） 💬（2）<div>根据周老师的指点，谁创建谁调用。以下是我想到一个办法调用throw方法(不知理解是否合理)：
function* foo() {
  yield 1
  yield 2
  yield 3
}
foo.prototype.throw = function(e) {
  console.log(&quot;Test Error &quot; + e)
}
let tor = foo()
for(let item of tor) {
  console.log(item)
  tor.throw(new Error(&#39;迭代器循环休内触发&#39;))
}</div>2021-08-12</li><br/><li><img src="" width="30px"><span>油菜</span> 👍（0） 💬（1）<div>&quot;用户在这里设计异常处理过程，那么 foo2() 中的 touch(x) 管理和涉及的资源都无法处理。&quot;
是指在“console.log() 调用或 for…of 循环中”处理异常么？ touch(x)和涉及的资源无法处理，是什么意思呢？ 是指touch(x)内部抛出异常，但catch不到异常么？
-------------------------------------
function touch(x) {
 try{
  if (x==2) throw new Error(&quot;hard break&quot;);
  }catch(c){
     console.log(&#39;c:&#39;+ c);
  }
}

&#47;&#47; 迭代函数
function foo2(x = 5) {
  return {
    next: () =&gt; {
      touch(x); &#47;&#47; some process methods
      return {done: !x, value: x &amp;&amp; x--};
    },
    &quot;return&quot;: () =&gt; console.log(&quot;RETURN!&quot;),
    &quot;throw&quot;: () =&gt; console.log(&quot;THROW!&quot;)
  }
}

&#47;&#47; 示例
var x = new Object;
x[Symbol.iterator] = foo2; &#47;&#47; default `x` is 

try{
		console.log(...x);
}catch(d){
  console.log(&#39;d:&#39;+ d);
}

结果：touch(x)可以处理异常
c:Error: hard break   
5 4 3 2 1</div>2020-11-13</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/12/d4/37/528a43e7.jpg" width="30px"><span>Elmer</span> 👍（0） 💬（1）<div>这个贴近语义的语法和解析为可执行结构的关系是什么呢</div>2020-07-07</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/15/45/da/71b7599d.jpg" width="30px"><span>antimony</span> 👍（0） 💬（1）<div>老师，请问一下这个迭代和递归的关系您是从sicp中了解到的吗？</div>2020-02-09</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/04/8d/005c2ff3.jpg" width="30px"><span>weineel</span> 👍（1） 💬（1）<div>四个思考题，都没能找到很好的答案。。。</div>2019-12-02</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/22/10/e2/35f2fc23.jpg" width="30px"><span>吉法师</span> 👍（0） 💬（0）<div>迭代感觉用不着啊……</div>2021-04-06</li><br/><li><img src="" width="30px"><span>油菜</span> 👍（0） 💬（0）<div>1 语言设计者有考虑到异常处理，但功能上还不够完善。类似写了个todo
2 使用者或设计者需要一种语法，能够接收所有参数。例如剩余参数 function foo(...x){console.log(x)}, 数组x可以接收所有入参。“为什么 ECMAScript 不提供一个表达式 &#47; 语句之外的概念来指代它”（老师可能是想说，之内的概念，文章标题已指出(...x)既不是表达式，也不是语句），可能是和现有的编译逻辑冲突。例如我们写程序，如果出现分支情况，最简单的做法是写个if判断，区分分支。表达式，语句，语法，可能是不同分支处理。

3 本人简单测试，以下几种都会触发tor.return。
for(var i of x ) {console.log(i);break};
for(var i of x ) {console.log(i); throw new Error(&#39;test&#39;)}
for(var i of x ) {console.log(i);continue};

4 只知其然，不知其所以然
&#47;&#47; 迭代函数
function foo6(x = 5) {
  return {
    &#47;&#47; foo2()中的next
    next: () =&gt; {
      return {done: !x, value: x &amp;&amp; x--};
    },
    &#47;&#47; foo3()中的return和throw
    &quot;return&quot;: () =&gt; console.log(&quot;RETURN!&quot;),
    &quot;throw&quot;: () =&gt; console.log(&quot;THROW!&quot;)
  }
}
var b = foo6();
b.next();&#47;&#47; { done: false, value: 5 }
b.next();&#47;&#47; { done: false, value: 4 }

&#47;&#47;yield用法
var x = new Object;
x[Symbol.iterator] = foo6;
function* g1() { yield* x}; 
var a = g1();
a.next(); &#47;&#47; { done: false, value: 5 }
a.next(); &#47;&#47; { done: false, value: 4 }</div>2020-11-13</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/15/ea/74/7dd9c65e.jpg" width="30px"><span>亦枫丶</span> 👍（0） 💬（0）<div>看了好久，对于第二个思考题恍然大悟，我想可以用文章开头的 

**“换而言之，可以通过更显式的、特指的或与应用概念更贴合的语法来表达新的语义。”**

这句话来解释吧，它只是“展开”逻辑的一种实现，叫它展开语法更为显式，与应用概念更贴合吧。</div>2020-04-03</li><br/>
</ul>