你好，我是海纳。

到目前为止，我们的虚拟机已经具备很多功能了，比如控制流、函数、对象、模块系统都已经构建完了。在这些机制的基础之上，我们才能完成迭代这一个基本功能。

迭代是 Python 中非常重要的一个机制，在实现列表和字典的时候，我们花了很大的精力介绍它们的迭代器。实际上，在 Python 中，自定义类型也可以定义迭代器。这种自定义迭代器需要依赖很多重要的功能作为基础，到目前为止，我们还差一个功能尚未完成，就是异常。因为 Python 虚拟机使用 StopIteration 异常来标志迭代结束。

这节课，我们将重点实现异常的处理机制。异常的处理需要增加新的控制流处理方式，我们从最简单的情况开始，逐步实现它。

## 实现 finally 子句

我们先看一个例子。

```python
def foo():
    try:
        print("hello")
        return
        print("hi")     # will not be executed
    finally:
        # will be executed
        print("world")

foo()
```

上述代码的执行结果是打印“hello”和“world”两个字符串。也就是说，return 语句（第 4 行）执行以后，函数并没有立即返回，而是打印完 “world”（第 8 行）以后才结束。
<div><strong>精选留言（4）</strong></div><ul>
<li><img src="https://static001.geekbang.org/account/avatar/00/3b/59/44/727b90a8.jpg" width="30px"><span>冯某</span> 👍（1） 💬（0）<div>这节有点难懂</div>2024-12-11</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/26/eb/d7/90391376.jpg" width="30px"><span>ifelse</span> 👍（0） 💬（0）<div>学习打卡</div>2024-11-11</li><br/><li><img src="https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKhqDU299SMLuWE5I3Rc1AGyqraV3v95FVaB9H1konxseOicGicLbQjKvF3G9DtGrZaG9icR0K6zMTYw/132" width="30px"><span>Geek_3d35fd</span> 👍（0） 💬（0）<div>cpython中POP_EXCEPT字节码实现是pop block之后就直接continue，执行紧挨着的下一个字节码了</div>2024-10-05</li><br/><li><img src="https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKhqDU299SMLuWE5I3Rc1AGyqraV3v95FVaB9H1konxseOicGicLbQjKvF3G9DtGrZaG9icR0K6zMTYw/132" width="30px"><span>Geek_3d35fd</span> 👍（0） 💬（0）<div>看代码有一个疑惑， 很长字节码部分执行到POP_EXCEPT弹出栈上异常对象，设置执行器状态是异常，会触发pop Block（type=setup_finally），重置状态为IS_OK，然后执行finally部分代码，改部分代码执行完紧接着执行END_FINALLY字节码，会重新设置状态为IS_EXCEPTION,  弹完BLOCK后状态始终是IS_EXCEPTION， 这样异常并没有捕获接着逐渐向上抛出了，正常应该在本函数捕获了啊</div>2024-10-05</li><br/>
</ul>