你好，我是徐逸。

在上节课中，我们学习了如何借助资源复用来降低Golang运行时的资源损耗，从而提升单机吞吐。在资源复用的技巧里，我们重点强调了协程池这一关键技巧。

有了协程并发的运用，自然少不了并发相关的技术。所以在今天的课程里，我们就来聊一聊协程**并发等待技术——WaitGroup类型和errgroup包**。只有熟练地掌握这些并发技术，我们才能够在面对各种并发场景时，更快、更好地解决各种并发问题。

首先，我们来想一个问题：倘若我们需要向多个下游发起并发请求，并且必须得等待所有请求返回时，你会用Golang的哪个并发类型来实现呢？

![](https://static001.geekbang.org/resource/image/46/63/4648cf524f607d5a56f025f83fb84863.jpg?wh=7128x3139 "图1 并发调用")

## WaitGroup类型

当面对这种场景时，常规解决方法是用Golang的基础并发类型WaitGroup。**WaitGroup的作用是阻塞等待多个并发任务执行完成**。WaitGroup类型主要包含下面几个方法。

```go
func (wg *WaitGroup) Add(delta int)
func (wg *WaitGroup) Done()
func (wg *WaitGroup) Wait()
```

- 第一个是 **Add方法**，在任务运行之前，需要调用Add方法，用于设置需要等待完成的任务数，Add方法传进去的数值之和，需要和任务数相等。
- 第二个是 **Done方法**，每个任务完成时，需要调用Done方法，用于告知WaitGroup对象已经有一个任务运行完成。
- 第三个是 **Wait方法**，当需要等待所有并发任务完成时，调用Wait方法，用于阻塞主协程。
<div><strong>精选留言（2）</strong></div><ul>
<li><img src="https://static001.geekbang.org/account/avatar/00/27/19/fe/d31344db.jpg" width="30px"><span>lJ</span> 👍（2） 💬（1）<div>可以基于 WaitGroup 和一个错误通道（error channel，容量不小于控制的协程并发数，避免阻塞）来收集并发协程中的错误信息，任务协程发生的错误写入err channel中，开启一个协程读取err channel。也可以初始化一个全局的错误切片errs，在协程出错时将err赋值给errs。

开源实现有
1、github.com&#47;facebookgo&#47;errgroup，扩展了标准库的sync.WaitGroup，errors收集协程执行时发生的错误
type Group struct {
	wg     sync.WaitGroup
	mu     sync.Mutex
	errors MultiError
}
2、github.com&#47;vardius&#47;gollback，gollback.All方法返回所有的错误

本质上都是通过err切片保存任务协程中的错误信息</div>2024-12-20</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/2d/17/17/ffc85c92.jpg" width="30px"><span>橙</span> 👍（1） 💬（1）<div>func TestCancel(t *testing.T) {
    results := make([]string, len(urls))
    &#47;&#47; 用WithContext函数创建Group对象
    eg, ctx := errgroup.WithContext(context.Background())
    for index, url := range urls {
        url := url
        index := index
        &#47;&#47; 调用Go方法
        eg.Go(func() error {
            select {
            case &lt;-ctx.Done(): &#47;&#47; select-done模式取消运行
                return errors.New(&quot;task is cancelled&quot;)
            default:
                &#47;&#47; Fetch the URL.
                resp, err := http.Get(url)
                if err != nil {
                    return err &#47;&#47; 返回错误
                }
                defer resp.Body.Close()
                body, err := io.ReadAll(resp.Body)
                if err != nil {
                    return err &#47;&#47; 返回错误
                }
                results[index] = string(body)
                return nil
            }
        })
    }
    &#47;&#47; Wait for all HTTP fetches to complete.
    &#47;&#47; 等待所有任务执行完成，并对错误进行处理
    if err := eg.Wait(); err != nil {
        fmt.Println(&quot;Failured fetched all URLs.&quot;)
    }
}
这个方法感觉直接用可以cancle的context会不会比较好，如果检测到错误直接cancel掉。现在感觉这个例子虽然支持cancel，虽然在讲cancel，但是例子没有支持cancel，看起来怪怪的。</div>2024-12-20</li><br/>
</ul>